/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PointWork.java
 *
 * Created on 5 mai 2013, 19:57:13
 */
package lotraco;

/**
 *
 * @author JAFOJIAL
 */
public class PointWork extends javax.swing.JPanel {

    private int choice = 0, idData = 0, project;
    
    /** Creates new form PointWork */
    public PointWork() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataParameters = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        boutonSaveData = new javax.swing.JButton();
        boutonCancelData = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        nameData = new javax.swing.JTextField();
        x = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        labelX = new javax.swing.JLabel();
        labelY = new javax.swing.JLabel();
        labelNameData = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelData = new javax.swing.JLabel();
        boutonNewData = new javax.swing.JButton();
        boutonEditData = new javax.swing.JButton();
        boutonDeleteData = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        boutonExportData = new javax.swing.JButton();
        boutonImportData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        scrollData = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data parameters", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.black)); // NOI18N

        boutonSaveData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boutonSaveData.setText("Save");
        boutonSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSaveDataActionPerformed(evt);
            }
        });

        boutonCancelData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boutonCancelData.setText("Cancel");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boutonSaveData, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(boutonCancelData)
                .addGap(10, 10, 10))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(boutonCancelData, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addComponent(boutonSaveData, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        nameData.setText("jTextField3");

        x.setText("jTextField1");

        y.setText("jTextField2");

        labelX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelX.setText("X");

        labelY.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelY.setText("Y");

        labelNameData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNameData.setText("Name");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(labelX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(labelNameData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(y, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(x, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNameData, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(nameData, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelX, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(y, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelY, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout DataParametersLayout = new javax.swing.GroupLayout(DataParameters.getContentPane());
        DataParameters.getContentPane().setLayout(DataParametersLayout);
        DataParametersLayout.setHorizontalGroup(
            DataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DataParametersLayout.setVerticalGroup(
            DataParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelData.setText("Manage yours data");

        boutonNewData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boutonNewData.setText("New");
        boutonNewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonNewDataActionPerformed(evt);
            }
        });

        boutonEditData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boutonEditData.setText("Edit");
        boutonEditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEditDataActionPerformed(evt);
            }
        });

        boutonDeleteData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boutonDeleteData.setText("Delete");
        boutonDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDeleteDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelData)
                .addGap(40, 40, 40)
                .addComponent(boutonNewData, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boutonEditData, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(boutonDeleteData)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelData, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(boutonDeleteData, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addComponent(boutonEditData, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
            .addComponent(boutonNewData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boutonExportData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boutonExportData.setText("Export");

        boutonImportData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boutonImportData.setText("Import");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonExportData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonImportData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boutonExportData, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boutonImportData, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollData.setViewportView(tableData);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollData, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollData, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boutonNewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonNewDataActionPerformed
        // TODO add your handling code here:
        
        nameData.setText("");
        x.setText("");
        y.setText("");
        
        DataParameters.setVisible(true);
        choice = 0;
        
    }//GEN-LAST:event_boutonNewDataActionPerformed

    private void boutonEditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEditDataActionPerformed
        // TODO add your handling code here:
        
        choice = 1;
        int ligne = tableData.getRowCount();
        for(int i = 0; i < ligne; i++){
            if(tableData.isRowSelected(i)){
                
                nameData.setText(tableData.getValueAt(i, 1).toString());
                x.setText(tableData.getValueAt(i, 2).toString());
                y.setText(tableData.getValueAt(i, 3).toString());
                
                idData = Integer.parseInt(tableData.getValueAt(i, 0).toString());
                //id.setText(tableData.getValueAt(i, 6).toString());
                
                DataParameters.setVisible(true);
            }
        }
    }//GEN-LAST:event_boutonEditDataActionPerformed

    private void boutonDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDeleteDataActionPerformed
        // TODO add your handling code here:
        
        int ligne = tableData.getRowCount();
        String nameD = null;
        Double xD = 0.0;
        Double yD = 0.0;
        for(int i = 0; i < ligne; i++){
            if(tableData.isRowSelected(i)){
                
            	nameD = tableData.getValueAt(i, 2).toString();
                xD = Double.parseDouble(tableData.getValueAt(i, 3).toString());
                yD = Double.parseDouble(tableData.getValueAt(i, 4).toString());
                
                project = Integer.parseInt(tableData.getValueAt(i, 0).toString());
                idData = Integer.parseInt(tableData.getValueAt(i, 1).toString());
            }
                
           PointGAUSS ptg = new PointGAUSS( project, idData , nameD, xD, yD);
           ptg.delete();
                
           tableData.removeAll();
           tableData.setModel(ptg.list());
           tableData.revalidate();
        }
        
}//GEN-LAST:event_boutonDeleteDataActionPerformed

    private void boutonSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSaveDataActionPerformed
        // TODO add your handling code here:
        
        String nameD = nameData.getText().toString();
        double xD = Double.parseDouble(x.getText().toString());
        double yD = Double.parseDouble(y.getText().toString());
        
        PointGAUSS pt = new PointGAUSS( project, idData, nameD , xD, yD);
        if(choice == 0){
            pt.create();
        } else if(choice == 1){
            pt.modify();
        }
        
        tableData.removeAll();
        tableData.setModel(pt.list());
        tableData.revalidate();
        
    }//GEN-LAST:event_boutonSaveDataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DataParameters;
    private javax.swing.JButton boutonCancelData;
    private javax.swing.JButton boutonDeleteData;
    private javax.swing.JButton boutonEditData;
    private javax.swing.JButton boutonExportData;
    private javax.swing.JButton boutonImportData;
    private javax.swing.JButton boutonNewData;
    private javax.swing.JButton boutonSaveData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelNameData;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JTextField nameData;
    private javax.swing.JScrollPane scrollData;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
