/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Welcome.java
 *
 * Created on 5 mai 2013, 10:54:42
 */
package lotraco;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author JAFOJIAL
 */
public class Welcome extends javax.swing.JFrame {

    private int choice = 0, idPro = 0;
    
    /** Creates new form Welcome */
    public Welcome() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectParameters = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        region = new javax.swing.JTextField();
        town = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelRegion = new javax.swing.JLabel();
        labelTown = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelAuthor = new javax.swing.JLabel();
        labelDescription = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        boutonSave = new javax.swing.JButton();
        boutonCancel = new javax.swing.JButton();
        PointGAUSSParameters = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        boutonEasy = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelProject = new javax.swing.JPanel();
        scrollProject = new javax.swing.JScrollPane();
        tableProject = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        boutonNew = new javax.swing.JButton();
        boutonEdit = new javax.swing.JButton();
        boutonDelete = new javax.swing.JButton();
        boutonOpen = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        ProjectParameters.setLocationByPlatform(true);
        ProjectParameters.setMinimumSize(new java.awt.Dimension(385, 360));
        ProjectParameters.setResizable(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Project parameters", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), java.awt.Color.black)); // NOI18N

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        labelName.setFont(new java.awt.Font("Tahoma", 1, 12));
        labelName.setText("Name");

        labelRegion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelRegion.setText("Region");

        labelTown.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTown.setText("Town");

        labelDate.setFont(new java.awt.Font("Tahoma", 1, 12));
        labelDate.setText("Date");

        labelAuthor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelAuthor.setText("Author");

        labelDescription.setFont(new java.awt.Font("Tahoma", 1, 12));
        labelDescription.setText("Description");

        boutonSave.setFont(new java.awt.Font("Tahoma", 1, 12));
        boutonSave.setText("Save");
        boutonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSaveActionPerformed(evt);
            }
        });

        boutonCancel.setFont(new java.awt.Font("Tahoma", 1, 12));
        boutonCancel.setText("Cancel");
        boutonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(boutonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boutonCancel)
                .addGap(80, 80, 80))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonSave, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(boutonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRegion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDescription))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(author, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(town, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(region, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRegion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(town, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescription))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout ProjectParametersLayout = new javax.swing.GroupLayout(ProjectParameters.getContentPane());
        ProjectParameters.getContentPane().setLayout(ProjectParametersLayout);
        ProjectParametersLayout.setHorizontalGroup(
            ProjectParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(ProjectParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProjectParametersLayout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ProjectParametersLayout.setVerticalGroup(
            ProjectParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
            .addGroup(ProjectParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProjectParametersLayout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout PointGAUSSParametersLayout = new javax.swing.GroupLayout(PointGAUSSParameters.getContentPane());
        PointGAUSSParameters.getContentPane().setLayout(PointGAUSSParametersLayout);
        PointGAUSSParametersLayout.setHorizontalGroup(
            PointGAUSSParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PointGAUSSParametersLayout.setVerticalGroup(
            PointGAUSSParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boutonEasy.setFont(new java.awt.Font("Tahoma", 1, 12));
        boutonEasy.setText("EASY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boutonEasy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boutonEasy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        panelProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableProject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title5", "Title6", "Title7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollProject.setViewportView(tableProject);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        boutonNew.setFont(new java.awt.Font("Tahoma", 1, 12));
        boutonNew.setText("New");
        boutonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonNewActionPerformed(evt);
            }
        });

        boutonEdit.setFont(new java.awt.Font("Tahoma", 1, 12));
        boutonEdit.setText("Edit");
        boutonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEditActionPerformed(evt);
            }
        });

        boutonDelete.setFont(new java.awt.Font("Tahoma", 1, 12));
        boutonDelete.setText("Delete");
        boutonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDeleteActionPerformed(evt);
            }
        });

        boutonOpen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boutonOpen.setText("Open");
        boutonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOpenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Yours projects");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(boutonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boutonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boutonDelete)
                .addGap(18, 18, 18)
                .addComponent(boutonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(boutonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(boutonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(boutonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(boutonNew, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelProjectLayout = new javax.swing.GroupLayout(panelProject);
        panelProject.setLayout(panelProjectLayout);
        panelProjectLayout.setHorizontalGroup(
            panelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollProject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelProjectLayout.setVerticalGroup(
            panelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollProject, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonNewActionPerformed
        // TODO add your handling code here:
        
        name.setText("");
        region.setText("");
        town.setText("");
        date.setText("");
        author.setText("");
        description.setText("");
        
        ProjectParameters.setVisible(true);
        choice = 0;
        
        
        
    }//GEN-LAST:event_boutonNewActionPerformed

    private void boutonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEditActionPerformed
        // TODO add your handling code here:
        
        choice = 1;
        int ligne = tableProject.getRowCount();
        for(int i = 0; i < ligne; i++){
            if(tableProject.isRowSelected(i)){
                
                name.setText(tableProject.getValueAt(i, 1).toString());
                region.setText(tableProject.getValueAt(i, 2).toString());
                town.setText(tableProject.getValueAt(i, 3).toString());
                date.setText(tableProject.getValueAt(i, 4).toString());
                author.setText(tableProject.getValueAt(i, 5).toString());
                description.setText(tableProject.getValueAt(i, 6).toString());
                idPro = Integer.parseInt(tableProject.getValueAt(i, 0).toString());
                //id.setText(tableProject.getValueAt(i, 6).toString());
                
                ProjectParameters.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_boutonEditActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nameActionPerformed

    private void boutonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSaveActionPerformed
        // TODO add your handling code here:
        
        //int idPro = Integer.parseInt(id.getText().toString());
        String namePro = name.getText().toString();
        String regionPro = region.getText().toString();
        String townPro = town.getText().toString();
        String authorPro = author.getText().toString();
        String descriptionPro = description.getText().toString();
        SimpleDateFormat simpleDate = new SimpleDateFormat("dd/MM/yyyy");
        Date datePro = null;
        try {
            datePro = simpleDate.parse(date.getText().toString());
        } catch (ParseException ex) {
        }
        System.out.println("Date: "+date.getText().toString());
        
        System.out.println(idPro);
        System.out.println(namePro);
        System.out.println(regionPro);
        System.out.println(townPro);
        System.out.println(datePro);
        System.out.println(authorPro);
        System.out.println(descriptionPro);
        
        Project pro = new Project( idPro, namePro , regionPro, townPro, date.getText().toString(), authorPro, descriptionPro);
        if(choice == 0){
            pro.create();
        }
        else if(choice == 1){
            pro.modify();
        }
        
        tableProject.removeAll();
        tableProject.setModel(pro.list());
        tableProject.revalidate();
}//GEN-LAST:event_boutonSaveActionPerformed

    private void boutonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCancelActionPerformed
        // TODO add your handling code here:
        
        ProjectParameters.dispose();
}//GEN-LAST:event_boutonCancelActionPerformed

    private void boutonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDeleteActionPerformed
        // TODO add your handling code here:
        
        int ligne = tableProject.getRowCount();
        for(int i = 0; i < ligne; i++){
            if(tableProject.isRowSelected(i)){
                
                String namePro = tableProject.getValueAt(i, 1).toString();
                String regionPro = tableProject.getValueAt(i, 2).toString();
                String townPro = tableProject.getValueAt(i, 3).toString();
                
                SimpleDateFormat simpleDate = new SimpleDateFormat("dd/MM/yy");
                Date datePro = null;
                try {
                    datePro = simpleDate.parse(tableProject.getValueAt(i, 4).toString());
                } catch (ParseException ex) {
                }
                
                String authorPro = tableProject.getValueAt(i, 5).toString();
                String descriptionPro = tableProject.getValueAt(i, 6).toString();
                idPro = Integer.parseInt(tableProject.getValueAt(i, 0).toString());
                
                Project pro = new Project( idPro, namePro , regionPro, townPro, tableProject.getValueAt(i, 4).toString(), authorPro, descriptionPro);
                pro.delete();
                
                tableProject.removeAll();
                tableProject.setModel(pro.list());
                tableProject.revalidate();
                //pro.list();
                //tableProject.remove(i);
                //tableProject.revalidate();
            }
        }
        
    }//GEN-LAST:event_boutonDeleteActionPerformed

    private void boutonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOpenActionPerformed
        // TODO add your handling code here:
        
        int ligne = tableProject.getRowCount();
        for(int i = 0; i < ligne; i++){
            if(tableProject.isRowSelected(i)){
                
                String namePro = tableProject.getValueAt(i, 1).toString();
                String regionPro = tableProject.getValueAt(i, 2).toString();
                String townPro = tableProject.getValueAt(i, 3).toString();
                
                SimpleDateFormat simpleDate = new SimpleDateFormat("dd/MM/yy");
                String datePro = tableProject.getValueAt(i, 4).toString();
                
                String authorPro = tableProject.getValueAt(i, 5).toString();
                String descriptionPro = tableProject.getValueAt(i, 6).toString();
                idPro = Integer.parseInt(tableProject.getValueAt(i, 0).toString());
                
                Project pro = new Project( idPro, namePro , regionPro, townPro, datePro, authorPro, descriptionPro);
                pro.open();
                
                panelProject.removeAll();
                PointWork point = new PointWork();
                panelProject.add(point);
                //panelProject.t
                panelProject.revalidate();
                
             
            }
        }
        
    }//GEN-LAST:event_boutonOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog PointGAUSSParameters;
    private javax.swing.JDialog ProjectParameters;
    private javax.swing.JTextField author;
    private javax.swing.JButton boutonCancel;
    private javax.swing.JButton boutonDelete;
    private javax.swing.JButton boutonEasy;
    private javax.swing.JButton boutonEdit;
    private javax.swing.JButton boutonNew;
    private javax.swing.JButton boutonOpen;
    private javax.swing.JButton boutonSave;
    private javax.swing.JTextField date;
    private javax.swing.JTextField description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAuthor;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelRegion;
    private javax.swing.JLabel labelTown;
    private javax.swing.JTextField name;
    private javax.swing.JPanel panelProject;
    private javax.swing.JTextField region;
    private javax.swing.JScrollPane scrollProject;
    private javax.swing.JTable tableProject;
    private javax.swing.JTextField town;
    // End of variables declaration//GEN-END:variables
}
